### ISSUE TITLE
Lockette is not auto lock

### ISSUE THREAD

**Issue by variananora** [leonidesu/AzN-Survival2#1]
Error logs:

[09:48:55] [Server thread/INFO]: [GriefPrevention] FarhanAce placed a sign @ world: x-164, z1033;[private];FarhanAce
[09:48:55] [Server thread/ERROR]: Could not pass event SignChangeEvent to LockettePro v2.9.0
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.canBuild(Lorg/bukkit/entity/Player;Lorg/bukkit/block/Block;)Z
	at me.crafter.mc.lockettepro.Dependency.isProtectedFrom(Dependency.java:95) ~[?:?]
	at me.crafter.mc.lockettepro.BlockPlayerListener.onManualLock(BlockPlayerListener.java:123) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor594.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-629]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-629]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-629]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2544) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-629]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-629]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Historia333** [comment]
fixed

**Comment by Arthzalcotl** [comment]
"Right click the block with a sign to lock" <<< ini dari lockette bukan? Kalau iya, ini ga jalan.

Gw harus manual tulis [private] dan nickname gw.
Lokasi: freebuild
Sekitaran jam 23:33-23:36
