### ISSUE TITLE
Illegal Stack error

### ISSUE THREAD

**Issue by leonidesu** [leonidesu/AzN-Survival2#37]
**Deskripsi Bug**
```
[18:03:42 ERROR]: Could not pass event PlayerFishEvent to IllegalStack v1.9.3c
java.lang.NoClassDefFoundError: fishing/FishAttempt
        at main.fListener.onFish(fListener.java:1425) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor148.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-629]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-629]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-629]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.EntityFishingHook.b(EntityFishingHook.java:496) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.ItemFishingRod.a(ItemFishingRod.java:33) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.ItemStack.a(ItemStack.java:338) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:419) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1401) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-629]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-629]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Cara menghasilkan bug**

**Hal yang seharusnya terjadi**

**Screenshot**

**Catatan tambahan**
@variananora

**Comment by variananora** [comment]
Fixed
